[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  base = "."

[build.environment]
  NODE_VERSION = "18.20.2"
  NPM_VERSION = "9.8.1"
  CI = false
  NODE_OPTIONS = "--openssl-legacy-provider"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
