[build]
  publish = "project/dist"
  command = "cd project && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--openssl-legacy-provider"

# Basic redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
