[build]
  base = "."
  publish = "dist"
  command = "npm install --legacy-peer-deps && npm run build"

# Configure redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  [plugins.inputs]
    paths = [
      "project/node_modules/.cache",
      "project/node_modules/.vite",
      "project/.svelte-kit",
      "project/.cache",
      "project/.next",
      "project/.yarn/cache"
    ]

# Build settings
[build.lifecycle]
  onBuild = "echo 'Starting build...'"
  onSuccess = "echo 'Build succeeded!'"
  onError = "echo 'Build failed!'"

# Configure build optimization
[build.optimization]
  bundle = true
  minify = true
  target = ["es2020", "edge88", "firefox78", "chrome87", "safari14"]

# Configure build processing
[build.processing]
  skip_processing = false

# Configure build publish
[build.publish]
  ignore = "git-cache|node_modules|.netlify|.vscode|.github|.git"

# Configure build headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self' https:;"
