[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--openssl-legacy-provider --max-old-space-size=4096"
  CI = "false"

# Configure build plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Configure build settings
[build.lifecycle]
  onBuild = "echo 'Starting build...'"
  onSuccess = "echo 'Build succeeded!'"
  onError = "echo 'Build failed!'"
