[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--openssl-legacy-provider --max-old-space-size=4096"
  CI = "false"
  NETLIFY_USE_YARN = "false"
  YARN_VERSION = "1.22.22"

# Cache configuration
[[plugins]]
  package = "@netlify/plugin-cache"
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
      "node_modules/.vite",
      ".svelte-kit",
      ".cache",
      ".next",
      ".yarn/cache"
    ]

# Build settings
[build.lifecycle]
  onBuild = "echo 'Starting build...'"
  onSuccess = "echo 'Build succeeded!'"
  onError = "echo 'Build failed!'"

# Configure build optimization
[build.optimization]
  bundle = true
  minify = true
  target = ["es2020", "edge88", "firefox78", "chrome87", "safari14"]

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
